//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpfpoep2
{
    using System;
    using System.Collections.Generic;
    
    public partial class gridstat
    {
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public string ModuleCode { get; set; }
        public Nullable<System.DateTime> Date_Recoreded { get; set; }
        public Nullable<decimal> Study_Hours_Remaining_For_Week { get; set; }
    }
}
